version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - metrocampus_net

  mongo-app:
    build:
      context: .
      dockerfile: build/mongodb/Dockerfile
    container_name: mongo-app
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/
    depends_on:
      - mongo
    networks:
      - metrocampus_net

  neo:
    image: neo4j:latest
    container_name: neo
    ports:
      - "7687:7687"
    networks:
      - metrocampus_net

  neo-app:
    build:
      context: .
      dockerfile: build/neo4j/Dockerfile
    container_name: neo4j-app
    ports:
      - "5001:5001"
    environment:
      - NEO_URL=neo4j://neo:7687
    depends_on:
      - neo
    networks:
      - metrocampus_net
networks:
  metrocampus_net:
    driver: bridge
